import { Icon } from '../components/Icon'
import { Logo } from '../components/Logo'
import { PublicHeader } from '../components/PublicHeader'
import { SectionHeading } from '../components/SectionHeading'

const products = [
  { title: 'Comprehensive', eyebrow: 'Broad protection', text: 'Cover for your vehicle with wider protection alongside third-party liability.', icon: 'shield' as const },
  { title: 'Third Party Fire & Theft', eyebrow: 'Essential plus', text: 'Third-party protection with added cover against fire and theft.', icon: 'car' as const },
  { title: 'Third Party', eyebrow: 'Essential cover', text: 'Straightforward third-party motor liability protection.', icon: 'receipt' as const },
]

export function HomePage() {
  return <div className="public-shell"><PublicHeader /><main>
    <section className="hero"><div className="container hero__grid"><div className="hero__copy"><span className="eyebrow eyebrow--red">Motor insurance, without the runaround.</span><h1>Cover your car.<br /><span>Keep moving.</span></h1><p className="hero__lead">Get a motor insurance quotation, accept your cover, pay securely with M-Pesa, and keep your policy in one place.</p><div className="hero__actions"><a className="button button--primary button--large" href="/register">Get a quotation <Icon name="arrow" /></a><a className="text-link" href="#how-it-works">See how it works <Icon name="arrow" /></a></div><div className="hero__proof"><span><Icon name="check" /> Transparent process</span><span><Icon name="check" /> M-Pesa payments</span><span><Icon name="check" /> Policy in one place</span></div></div>
      <div className="hero-card-wrap" aria-hidden="true"><div className="hero-glow" /><div className="hero-product-card"><div className="hero-card__top"><span className="mini-label">MOTOR COVER</span><Icon name="shield" /></div><div className="hero-product-card__headline">Choose your cover.<br />We'll help with the rest.</div><div className="hero-product-list">{products.map((product,index)=><div className={`hero-product-row ${index===0?'hero-product-row--active':''}`} key={product.title}><div className="hero-product-row__icon"><Icon name={product.icon} /></div><div><strong>{product.title}</strong><span>{product.eyebrow}</span></div><Icon name="chevron" /></div>)}</div><div className="hero-card__footer">Jodam Insurance Agency</div></div></div>
    </div></section>
    <section className="trust-strip"><div className="container trust-strip__inner"><span>JODAM INSURANCE AGENCY</span><span className="trust-strip__dot" /><span>Professional. Transparent. Customer-first.</span></div></section>
    <section id="motor" className="section section--soft"><div className="container"><SectionHeading eyebrow="Motor insurance" title="The cover we can arrange for you." body="Choose the type of motor protection you are looking for. Jodam will take you through the quotation and policy journey."/><div className="product-grid">{products.map(product=><article className="product-card" key={product.title}><div className="product-card__top"><div className="feature-icon"><Icon name={product.icon} /></div><span className="eyebrow">{product.eyebrow}</span></div><h3>{product.title}</h3><p>{product.text}</p><a className="text-link" href="/register">Start an enquiry <Icon name="arrow" /></a></article>)}</div></div></section>
    <section id="how-it-works" className="section"><div className="container split-section"><SectionHeading eyebrow="How it works" title="A clear journey from enquiry to cover." body="No unnecessary steps. Every stage is visible, and every important action has a clear next move."/><div className="step-list">{['Submit your motor application','Receive and review your quotation','Accept your quotation and issue your policy','Pay securely through M-Pesa','Manage your policy and claims online'].map((step,index)=><div className="step" key={step}><span className="step__number">0{index+1}</span><span>{step}</span><Icon name="arrow" /></div>)}</div></div></section>
    <section id="contact" className="section section--dark"><div className="container support-banner"><div><span className="eyebrow">Jodam Insurance Agency</span><h2>Insurance with a Difference.</h2><p>Built around professionalism, honesty, clear communication and customer satisfaction.</p></div><div className="support-banner__actions"><a className="button button--light" href="/register">Start with motor insurance <Icon name="arrow" /></a><a className="support-contact-link" href="mailto:twirextras@gmail.com">twirextras@gmail.com</a></div></div></section>
  </main><footer className="footer"><div className="container footer__inner"><Logo compact /><span>© {new Date().getFullYear()} Jodam Insurance Agency</span><span>Motor Insurance Portal</span></div></footer></div>
}
