import { FormEvent, useState } from 'react'
import { useNavigate, useSearchParams } from 'react-router-dom'
import { useAuth } from '../context/AuthContext'
import { Logo } from '../components/Logo'
import { Icon } from '../components/Icon'

export function LoginPage() {
  const navigate = useNavigate(); const [searchParams] = useSearchParams(); const { signIn } = useAuth()
  const [username,setUsername]=useState(''); const [password,setPassword]=useState(''); const [showPassword,setShowPassword]=useState(false); const [error,setError]=useState(''); const [busy,setBusy]=useState(false)
  async function submit(event:FormEvent){event.preventDefault();setError('');setBusy(true);try{const role=await signIn(username.trim(),password);const requested=searchParams.get('returnTo');const fallback=role==='CUSTOMER'?'/app':'/staff';const allowed=requested?.startsWith(role==='CUSTOMER'?'/app':'/staff')?requested:fallback;navigate(allowed,{replace:true})}catch(err){setError(err instanceof Error?err.message:'Unable to sign in')}finally{setBusy(false)}}
  return <div className="auth-shell"><div className="auth-shell__brand"><Logo /></div><div className="auth-card"><div className="auth-card__intro"><span className="eyebrow eyebrow--red">Customer portal</span><h1>Welcome back.</h1><p>Sign in to manage your motor insurance.</p></div>{searchParams.get('sessionExpired')==='1'&&<div className="info-strip">Your session expired. Sign in again to continue where you left off.</div>}{error&&<div className="form-error">{error}</div>}<form onSubmit={submit} className="form-stack"><label>Username<input value={username} onChange={e=>setUsername(e.target.value)} placeholder="Your username" autoComplete="username" required /></label><label>Password<span className="password-input"><input value={password} onChange={e=>setPassword(e.target.value)} type={showPassword?'text':'password'} placeholder="Your password" autoComplete="current-password" required /><button type="button" className="password-toggle" onClick={()=>setShowPassword(v=>!v)} aria-label={showPassword?'Hide password':'Show password'} title={showPassword?'Hide password':'Show password'}><Icon name={showPassword ? "eye-off" : "eye"} /></button></span></label><button className="button button--primary button--full" disabled={busy}>{busy?'Signing in…':'Sign in'}</button></form><p className="auth-switch">New to Jodam? <a href="/register">Create your account</a></p></div><p className="auth-footnote">Insurance with a Difference</p></div>
}
